import Head from "next/head";
import Navbar from "@/components/navbar";
import styles from '@/styles/GetInvolved.module.css';
import Assistant from "@/components/Assistant";
import Footer from "@/components/Footer";
import Link from "next/link";
export default function GetInvolved (){
    return(
        <>
            <Head>
                <title>Abhilasha Samiti</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
                <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet"/>
            </Head>
            <div className={styles.container}>
                <Assistant/>
                <div className={styles.topDiv}>
                        <Navbar/>
                </div>
                        
                    <div className={styles.newsDiv}>
                        <div className={styles.newsDiv_top}>
                            <h2 className={styles.newsDiv_top_header}>Get Involved</h2>
                        </div>
                        <div className={styles.newsDiv_bottom}>
                        
                                <div className={styles.newsDiv_block}>
                                        <div className={styles.newsDiv_block_left}>
                                                <div className={styles.newsDiv_block_left_top}>
                                                    <h2 className={styles.newsDiv_block_header}>Together, we create <br/> lasting____  impact</h2>

                                                </div>

                                                <div className={styles.newsDiv_block_left_bottom}>
                                                    <p>Your support can change lives and build brighter futures. Join us in making a difference today.</p>
                                                </div>

                                                <div className={styles.newsDiv_block_left_button}>
                                                    <button className={styles.donateButton}>
                                                        <p className={styles.donateButton_paragraph}>Donate Now</p>
                                                        <div className={styles.donateButton_arrow}>
                                                                <img src="/next.png" width={20} height={20}/>
                                                        </div>
                                                    </button>
                                                </div>
                                        </div>
                                        <div className={styles.newsDiv_block_right}>
                                                    <div className={styles.newsDiv_block_right_photo}>
                                                            <img src="/children.avif" className={styles.newsDiv_block_right_photo_image} width={150} height={150}/>
                                                        
                                                    </div>
                                        </div>
                                </div>

                                <div className={styles.newsDiv_block_second}>
                                            <div className={styles.newsDiv_block_second_left}>
                                                        <div className={styles.newsDiv_block_second_left_photo}>
                                                                <img src="/jalutsav.jpg" className={styles.newsDiv_block_second_left_photo_image} width={150} height={150}/>
                                                        </div>
                                            </div>

                                            <div className={styles.newsDiv_block_second_right}>
                                                    <div className={styles.newsDiv_block_second_right_top}>
                                                        <h2 className={styles.newsDiv_block_second_header}>Become a volunteer</h2>
                                                      
                                                    </div>

                                                    <div className={styles.newsDiv_block_second_right_bottom}>
                                                        <p>Join our team of volunteers and help drive our mission forward with your valuable contribution.</p>
                                                    </div>
                                                    <div className={styles.newsDiv_block_second_right_button}>
                                                            <Link className={styles.applyButton} href='https://forms.gle/CZnHjuRESBP3zYMG9'target="on_blank">
                                                                    <p className={styles.donateButton_paragraph}>Apply Now</p>
                                                                    <div className={styles.donateButton_arrow}>
                                                                            <img src="/green-next.png" width={20} height={20}/>
                                                                    </div>
                                                            </Link>
                                                    </div>
                                            </div>
                                            {/* <br/> we run a school and implement various developmental activities in 50 villages, aiming to provide quality education and reduce rural migration. */}
                                </div>

                                <div className={styles.newsDiv_block}>
                                        <div className={styles.newsDiv_block_left}>
                                                <div className={styles.newsDiv_block_left_top}>
                                                    <h2 className={styles.newsDiv_block_header}>Start Your Journey: <br/> Intern with Us</h2>

                                                </div>

                                                <div className={styles.newsDiv_block_left_bottom}>
                                                    <p>Gain real-world experience, develop new skills, and make an impact by joining our team as an intern.</p>
                                                </div>

                                                <div className={styles.newsDiv_block_left_button}>
                                                    <Link className={styles.internButton} href={'https://forms.gle/WzQoVMGaQJq7KAUh8'} target="on_blank">
                                                    <p className={styles.donateButton_paragraph}>Intern Now</p>
                                                    <div className={styles.donateButton_arrow}>
                                                            <img src="/intern-next.png" width={20} height={20}/>
                                                    </div>
                                                    </Link>
                                                </div>
                                        </div>
                                        <div className={styles.newsDiv_block_right}>
                                                    <div className={styles.newsDiv_block_right_photo}>
                                                            <img src="/intern.jpg" className={styles.newsDiv_block_right_photo_image} width={150} height={150}/>
                                                        
                                                    </div>
                                        </div>
                                </div>
                        </div>
                    </div>
                    <Footer/>
            </div>
        </>
    )
}