import Head from "next/head";
import Navbar from "@/components/navbar";
import styles from '@/styles/Projects.module.css';
import Footer from "@/components/Footer";
import Assistant from "@/components/Assistant";
export default function Projects (){
    return(
        <>  
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
                <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet"/>
                </Head>

                <div className={styles.container}>
                <Assistant/>
                    <div className={styles.topDiv}>
                         <Navbar/>
                    </div>
                    <div className={styles.newsDiv}>
                            <div className={styles.newsDiv_top}>

                                        <h2>Projects by Abhilasha</h2>

                            </div>
                            <div className={styles.newsDiv_bottom}>
                       
                                    <div className={styles.newsDiv_block_second}>
                                                <div className={styles.newsDiv_block_second_left}>
                                                            <div className={styles.newsDiv_block_second_left_photo}>
                                                                    <img src="/securerhimalaya.png" className={styles.newsDiv_block_second_left_photo_image} width={150} height={150}/>
                                                            </div>
                                                </div>

                                                <div className={styles.newsDiv_block_second_right}>
                                                        <div className={styles.newsDiv_block_second_right_top}>
                                                            <h2 className={styles.newsDiv_block_header}>Securer Himalaya</h2>
                                                            <div className={styles.newsDiv_block_spacer}></div>
                                                        </div>

                                                        <div className={styles.newsDiv_block_second_right_bottom}>
                                                            <p>Our mission is to improve the lives of people in remote Pithoragarh, Uttarakhand.</p>
                                                        </div>
                                                </div>
                                                
                                                {/* <br/> we run a school and implement various  developmental activities in 50 villages,  aiming to provide quality education  and reduce rural migration. */}
                                    </div>
                                    <div className={styles.newsDiv_block}>
                                            <div className={styles.newsDiv_block_left}>
                                                    <div className={styles.newsDiv_block_left_top}>
                                                        <h2 className={styles.newsDiv_block_header}>Spring Shed Management Training</h2>
                                                        <div className={styles.newsDiv_block_spacer}></div>
                                                    </div>

                                                    <div className={styles.newsDiv_block_left_bottom}>
                                                        <p>We recently had our big meet-up at Kashipur with over 120 + schools joining on shared vision of making education more accessible</p>
                                                    </div>
                                            </div>
                                            <div className={styles.newsDiv_block_right}>
                                                        <div className={styles.newsDiv_block_right_photo}>
                                                                <img src="/SpringShed.png" className={styles.newsDiv_block_right_photo_image} width={150} height={150}/>
                                                        </div>
                                            </div>
                                    </div>
                                    <div className={styles.newsDiv_block_second}>
                                                <div className={styles.newsDiv_block_second_left}>
                                                            <div className={styles.newsDiv_block_second_left_photo}>
                                                                    <img src="/AccountingTraining.png" className={styles.newsDiv_block_second_left_photo_image} width={150} height={150}/>
                                                            </div>
                                                </div>

                                                <div className={styles.newsDiv_block_second_right}>
                                                        <div className={styles.newsDiv_block_second_right_top}>
                                                            <h2 className={styles.newsDiv_block_header}>Accounting Training</h2>
                                                            <div className={styles.newsDiv_block_spacer}></div>
                                                        </div>

                                                        <div className={styles.newsDiv_block_second_right_bottom}>
                                                            <p>Our mission is to improve the lives of people in remote Pithoragarh, Uttarakhand.</p>
                                                        </div>
                                                </div>
                                                
                                                {/* <br/> we run a school and implement various  developmental activities in 50 villages,  aiming to provide quality education  and reduce rural migration. */}
                                    </div>
                                    <div className={styles.newsDiv_block}>
                                            <div className={styles.newsDiv_block_left}>
                                                    <div className={styles.newsDiv_block_left_top}>
                                                        <h2 className={styles.newsDiv_block_header}>Nursery Development</h2>
                                                        <div className={styles.newsDiv_block_spacer}></div>
                                                    </div>

                                                    <div className={styles.newsDiv_block_left_bottom}>
                                                        <p>We recently had our big meet-up at Kashipur with over 120 + schools joining on shared vision of making education more accessible</p>
                                                    </div>
                                            </div>
                                            <div className={styles.newsDiv_block_right}>
                                                        <div className={styles.newsDiv_block_right_photo}>
                                                                <img src="/WomenComponent.png" className={styles.newsDiv_block_right_photo_image} width={150} height={150}/>
                                                        </div>
                                            </div>
                                    </div>
                                    <div className={styles.newsDiv_block_second}>
                                                <div className={styles.newsDiv_block_second_left}>
                                                            <div className={styles.newsDiv_block_second_left_photo}>
                                                                    <img src="/VanPanchayat.png" className={styles.newsDiv_block_second_left_photo_image} width={150} height={150}/>
                                                            </div>
                                                </div>

                                                <div className={styles.newsDiv_block_second_right}>
                                                        <div className={styles.newsDiv_block_second_right_top}>
                                                            <h2 className={styles.newsDiv_block_header}>Van Panchayat Workshop</h2>
                                                            <div className={styles.newsDiv_block_spacer}></div>
                                                        </div>

                                                        <div className={styles.newsDiv_block_second_right_bottom}>
                                                            <p>Our mission is to improve the lives of people in remote Pithoragarh, Uttarakhand.</p>
                                                        </div>
                                                </div>
                                                
                                                {/* <br/> we run a school and implement various  developmental activities in 50 villages,  aiming to provide quality education  and reduce rural migration. */}
                                    </div>
                                    <div className={styles.newsDiv_block}>
                                            <div className={styles.newsDiv_block_left}>
                                                    <div className={styles.newsDiv_block_left_top}>
                                                        <h2 className={styles.newsDiv_block_header}>Capacity Buildup Program</h2>
                                                        <div className={styles.newsDiv_block_spacer}></div>
                                                    </div>

                                                    <div className={styles.newsDiv_block_left_bottom}>
                                                        <p>We recently had our big meet-up at Kashipur with over 120 + schools joining on shared vision of making education more accessible</p>
                                                    </div>
                                            </div>
                                            <div className={styles.newsDiv_block_right}>
                                                        <div className={styles.newsDiv_block_right_photo}>
                                                                <img src="/CapacityBuildup.png" className={styles.newsDiv_block_right_photo_image} width={150} height={150}/>
                                                        </div>
                                            </div>
                                    </div>
                                    
                                   
                            </div>
                    </div>
                    <Footer/>
                </div>
        </>
    )
}